#!/bin/bash
# Regenerate files.mk from Bender.yml (needs bender). Run after adding or removing RTL files.
set -euo pipefail
root="$(cd "$(dirname "$0")/../../.." && pwd)"
flist="$(cd "$root" && bender script flist-plus -t asic -t sky130 -t rtl -t synthesis)"
{
  echo "# Generated by asic/sky130/croc/gen_flist.sh from Bender.yml (targets: asic sky130 rtl synthesis)"
  echo "export CROC_VERILOG_FILES = \\"
  grep -E '\.s?v$' <<<"$flist" | sed "s|$root|\$(CROC_ROOT)|; s|^|  |; s|$| \\\\|"
  echo ""
  echo "export CROC_INCLUDE_DIRS = \\"
  grep '^+incdir+' <<<"$flist" | sed "s|+incdir+$root|\$(CROC_ROOT)|; s|^|  |; s|$| \\\\|"
  echo ""
} > "$(dirname "$0")/files.mk"
